apiVersion: 1

contactPoints:
  - orgId: 1
    name: ntfy-homelab
    receivers:
      - uid: ntfy_homelab
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://127.0.0.1/homelab-alerts?template=grafana
          httpMethod: POST
          maxAlerts: "10"
