apiVersion: 1

groups:
  - orgId: 1
    name: pve01 - SSD SMART health failed
    folder: Homelab - Storage
    interval: 1m

    rules:
      - uid: pve01smartssdh
        title: pve01 - SSD SMART health failed
        condition: C

        data:
          - refId: A
            relativeTimeRange:
              from: 900
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: |
                homelab_smart_device_health{instance="192.168.10.10:9100",device="pve-ssd"}
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

          - refId: C
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold

        noDataState: NoData
        execErrState: Error
        for: 1m
        keepFiringFor: 1m

        annotations:
          summary: Proxmox SSD SMART health failed
          description: The Proxmox SSD is reporting a failing SMART overall-health status.

        labels:
          category: smart
          host: pve01
          severity: critical
          device: pve-ssd

        isPaused: false

        notification_settings:
          receiver: ntfy-homelab
