apiVersion: 1
groups:
    - orgId: 1
      name: filesystem
      folder: Homelab
      interval: 1m
      rules:
        - uid: efx1qeyy142rkf
          title: pve01 - Filesystem usage critical
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: |-
                    100 * (
                      1 -
                      (
                        node_filesystem_avail_bytes{
                          instance="192.168.10.10:9100",
                          fstype!~"tmpfs|fuse|overlay"
                        }
                        /
                        node_filesystem_size_bytes{
                          instance="192.168.10.10:9100",
                          fstype!~"tmpfs|fuse|overlay"
                        }
                      )
                    )
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 5m
          keepFiringFor: 1m
          labels:
            category: filesystem
            host: pve01
            severity: critical
          isPaused: false
          notification_settings:
            receiver: ntfy-homelab
        - uid: efx29lp5kdts0f
          title: pve01 - Filesystem usage warning
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: |-
                    100 * (
                      1 -
                      (
                        node_filesystem_avail_bytes{
                          instance="192.168.10.10:9100",
                          fstype!~"tmpfs|fuse|overlay"
                        }
                        /
                        node_filesystem_size_bytes{
                          instance="192.168.10.10:9100",
                          fstype!~"tmpfs|fuse|overlay"
                        }
                      )
                    )
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 10m
          keepFiringFor: 1m
          annotations: {}
          labels:
            category: filesystem
            host: pve01
            severity: high
          isPaused: false
          notification_settings:
            receiver: ntfy-homelab
