apiVersion: 1
groups:
    - orgId: 1
      name: Memory
      folder: Homelab
      interval: 1m
      rules:
        - uid: efx2aslu5h81se
          title: pve01 - Memory usage warning
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: |-
                    100 * (
                      1 -
                      (
                        node_memory_MemAvailable_bytes{
                          instance="192.168.10.10:9100"
                        }
                        /
                        node_memory_MemTotal_bytes{
                          instance="192.168.10.10:9100"
                        }
                      )
                    )
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 10m
          keepFiringFor: 1m
          annotations:
            description: Available memory on pve01 has remained below 10% for 10 minutes.
            summary: pve01 memory pressure high
          labels:
  	    host: pve01
            category: memory
            severity: warning
          isPaused: false
          notification_settings:
            receiver: ntfy-homelab

