apiVersion: 1

groups:
  - orgId: 1
    name: pve01 - SMART collector failed
    folder: Homelab - Monitoring
    interval: 1m

    rules:
      - uid: pve01smartcolf
        title: pve01 - SMART collector failed
        condition: C

        data:
          - refId: A
            relativeTimeRange:
              from: 900
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: |
                homelab_smart_collector_success{instance="192.168.10.10:9100"}
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

          - refId: C
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold

        noDataState: Alerting
        execErrState: Error
        for: 2m
        keepFiringFor: 1m

        annotations:
          summary: SMART collector failed on pve01
          description: The SMART collector is reporting an unsuccessful execution.

        labels:
          category: smart
          host: pve01
          severity: critical


        isPaused: false

        notification_settings:
          receiver: ntfy-homelab
