apiVersion: 1
groups:
    - orgId: 1
      name: Down
      folder: Homelab
      interval: 1m
      rules:
        - uid: bfx1nl4wrzugwf
          title: pve01 - Node down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: max(up{job="pve01"}) or vector(0)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 2m
          annotations: {}
          labels:
            category: down
            host: pve01
            severity: critical
          isPaused: false
          notification_settings:
            receiver: ntfy-homelab

